# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
   #- name: Test with pytest
    #  run: |
        #pytest
  #deploy:
    #runs-on: ubuntu-latest
   # steps:
    #- uses: actions/checkout@v1
   # - name: deploy to server 
    #  uses: akhileshns/heroku-deploy@v3.12.14 
    #  with:
      #  email: ${{ secrets.HEROKU_EMAIL }}
      #  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            
        # Name of the heroku application to which the build is to be sent.
       # heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
       # script: uvicorn api:app --host=0.0.0.0 --port=${PORT:-5000}
      
    
